<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-03-02T11:02:17 IST" name="Default suite" finished-at="2024-03-02T11:02:51 IST" duration-ms="33911">
    <groups>
    </groups>
    <test started-at="2024-03-02T11:02:17 IST" name="Default test" finished-at="2024-03-02T11:02:51 IST" duration-ms="33911">
      <class name="testcases.logIn">
        <test-method is-config="true" signature="launchurl()[pri:0, instance:testcases.logIn@1a6d8329]" started-at="2024-03-02T11:02:19 IST" name="launchurl" finished-at="2024-03-02T11:02:30 IST" duration-ms="11239" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchurl -->
        <test-method signature="loginWithValidCredentials(java.lang.String,java.lang.String)[pri:0, instance:testcases.logIn@1a6d8329]" started-at="2024-03-02T11:02:30 IST" name="loginWithValidCredentials" data-provider="testDataSeab" finished-at="2024-03-02T11:02:36 IST" duration-ms="5337" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[ao1@seab]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[c]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [https://ecw.excelindia.com/TESTR3/home] but found [https://ecw.excelindia.com/TESTR3/admin/login]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [https://ecw.excelindia.com/TESTR3/home] but found [https://ecw.excelindia.com/TESTR3/admin/login]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at Pages.login_pom.clickLogin(login_pom.java:52)
at common.loginCommon.clickLoginButton(loginCommon.java:27)
at testcases.logIn.loginWithValidCredentials(logIn.java:17)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginWithValidCredentials -->
        <test-method is-config="true" signature="launchurl()[pri:0, instance:testcases.logIn@1a6d8329]" started-at="2024-03-02T11:02:36 IST" name="launchurl" finished-at="2024-03-02T11:02:46 IST" duration-ms="10208" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchurl -->
        <test-method signature="loginWithValidCredentials(java.lang.String,java.lang.String)[pri:0, instance:testcases.logIn@1a6d8329]" started-at="2024-03-02T11:02:46 IST" name="loginWithValidCredentials" data-provider="testDataSeab" finished-at="2024-03-02T11:02:51 IST" duration-ms="5501" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[eo1@seab.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[a]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginWithValidCredentials -->
      </class> <!-- testcases.logIn -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
